export const NOTIFICATION_ENV_KEYS = {
  PORT: 'PORT',
  FRONTEND_URL: 'FRONTEND_URL',
  RABBITMQ_URL: 'RABBITMQ_URL',
  NOTIFICATION_QUEUE_NAME: 'NOTIFICATION_QUEUE_NAME',
  NOTIFICATION_DEAD_LETTER_QUEUE_NAME: 'NOTIFICATION_DEAD_LETTER_QUEUE_NAME',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_SECURE: 'SMTP_SECURE',
  SMTP_FROM_EMAIL: 'SMTP_FROM_EMAIL',
  SMTP_FROM_NAME: 'SMTP_FROM_NAME',
} as const;

export type NotificationEnvKey = keyof typeof NOTIFICATION_ENV_KEYS;

export type NotificationEnvRecord = Record<NotificationEnvKey, string>;
