export const NOTIFICATION_ENV_KEYS = {
  PORT: 'PORT',
  FRONTEND_URL: 'FRONTEND_URL',
  RABBITMQ_URL: 'RABBITMQ_URL',
  NOTIFICATION_QUEUE_NAME: 'NOTIFICATION_QUEUE_NAME',
  NOTIFICATION_DEAD_LETTER_QUEUE_NAME: 'NOTIFICATION_DEAD_LETTER_QUEUE_NAME',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_SECURE: 'SMTP_SECURE',
  SMTP_FROM_EMAIL: 'SMTP_FROM_EMAIL',
  SMTP_FROM_NAME: 'SMTP_FROM_NAME',
  GATEWAY_SERVICE_GRPC_URL: 'GATEWAY_SERVICE_GRPC_URL',
  PRISMA_DB_URL: 'PRISMA_DB_URL',
  NOTIFICATION_RECIPIENT_GRPC_TIMEOUT_MS: 'NOTIFICATION_RECIPIENT_GRPC_TIMEOUT_MS',
  NOTIFICATION_RECIPIENT_GRPC_MAX_RETRIES: 'NOTIFICATION_RECIPIENT_GRPC_MAX_RETRIES',
  NOTIFICATION_RECIPIENT_GRPC_RETRY_BACKOFF_MS: 'NOTIFICATION_RECIPIENT_GRPC_RETRY_BACKOFF_MS',
  PAYMENT_NOTIFICATION_QUEUE_NAME: 'PAYMENT_NOTIFICATION_QUEUE_NAME',
  PAYMENT_NOTIFICATION_DLQ_NAME: 'PAYMENT_NOTIFICATION_DLQ_NAME',
  PAYMENT_NOTIFICATION_MAX_ATTEMPTS: 'PAYMENT_NOTIFICATION_MAX_ATTEMPTS',
  PAYMENT_NOTIFICATION_RETRY_BACKOFF_MS: 'PAYMENT_NOTIFICATION_RETRY_BACKOFF_MS',
  PAYMENT_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS:
    'PAYMENT_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS',
} as const;

export type NotificationEnvKey = keyof typeof NOTIFICATION_ENV_KEYS;

export type NotificationEnvRecord = Record<NotificationEnvKey, string>;
