syntax = "proto3";

package inctagram.user.v1;

message GetUserByIdRequest {
  string user_id = 1;
}

message User {
  string id = 1;
  string email = 2;
  string username = 3;
}

message GetUserByIdResponse {
  User user = 1;
}

message GetNotificationRecipientContextRequest {
  string user_id = 1;
}

message GetNotificationRecipientContextResponse {
  string user_id = 1;
  string email = 2;
  string user_name = 3;
}

service UserService {
  rpc GetUserById(GetUserByIdRequest)
      returns (GetUserByIdResponse);
  rpc GetNotificationRecipientContext(GetNotificationRecipientContextRequest)
      returns (GetNotificationRecipientContextResponse);
}