apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           securityContext:
             allowPrivilegeEscalation: false
             runAsNonRoot: true      # опционально, но хорошая практика
             runAsUser: 1000         # опционально
           ports:
             - containerPort: PORT_CONTAINER
           env:
             - name: FRONTEND_URL
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: FRONTEND_URL
             - name: RABBITMQ_URL
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: RABBITMQ_URL
             - name: NOTIFICATION_QUEUE_NAME
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: NOTIFICATION_QUEUE_NAME
             - name: NOTIFICATION_DEAD_LETTER_QUEUE_NAME
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: NOTIFICATION_DEAD_LETTER_QUEUE_NAME
             - name: SMTP_HOST
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_HOST
             - name: SMTP_PORT
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_PORT
             - name: SMTP_USER
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_USER
             - name: SMTP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_PASSWORD
             - name: SMTP_FROM_EMAIL
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_FROM_EMAIL
             - name: SMTP_FROM_NAME
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: SMTP_FROM_NAME
             - name: PORT
               valueFrom:
                 secretKeyRef:
                   name: micro-notification-service-28-04-2026-production-config-secret
                   key: PORT
