apiVersion: v1
kind: Service

metadata:
  name: micro-notification-service
  namespace: NAMESPACE

spec:
  selector:
    project: PROJECT
  ports:
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: 50054
