version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: inctagram-rabbitmq
    ports:
      - '5672:5672' # Порт для подключения микросервисов
      - '15672:15672' # Порт для админки (UI)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Сохраняем данные очередей при перезапуске
    restart: always

volumes:
  rabbitmq_data:
