apiVersion: v1
kind: Service

metadata:
  name: micro-payment-service
  namespace: NAMESPACE

spec:
  selector:
    project: PROJECT
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
