apiVersion: v1
kind: Service

metadata:
  name: micro-post-service
  namespace: nymbi-org

spec:
  selector:
    project: micro-post-service-31-05-2026

  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
