// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
// Getting process.env.PRISMA_DB_URL from .env.development file located at the path specified below
dotenv.config({ path: `apps/main-gateway-service/.env.${process.env.NODE_ENV}` });
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: './schema.prisma',
  migrations: {
    path: './migrations',
  },
  datasource: {
    url: process.env.PRISMA_DB_URL,
  },
});
